services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: learnify_db
      POSTGRES_USER: learnify_user
      POSTGRES_PASSWORD: quetvaque700716
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
    name: learnify-postgres_data