# Generated by Django 4.2 on 2026-03-19 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField()),
                ('easy_factor_after', models.FloatField()),
                ('interval_after', models.IntegerField()),
                ('repetitions_after', models.IntegerField()),
                ('next_review_at_after', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='flashcards.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cardreview',
            index=models.Index(fields=['card', 'reviewed_at'], name='study_cardr_card_id_233fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='cardreview',
            index=models.Index(fields=['user', 'reviewed_at'], name='study_cardr_user_id_89b26d_idx'),
        ),
    ]
