# Generated by Django 4.2 on 2026-03-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardreview',
            old_name='easy_factor_after',
            new_name='ease_factor_after',
        ),
    ]
