# Generated by Django 4.2 on 2026-03-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='card_type',
            field=models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('phrase', 'Phrase'), ('qa', 'Q&A'), ('qa_en', 'Q&A English')], default='vocabulary', max_length=20),
        ),
        migrations.AlterField(
            model_name='generationsession',
            name='domain',
            field=models.CharField(choices=[('english', 'English Learning'), ('academic', 'Academic / Chuyên ngành'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
