# Generated by Django 4.2 on 2026-03-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_alter_flashcard_card_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='practice_questions',
            field=models.JSONField(blank=True, default=list, help_text='Câu hỏi luyện tập cho grammar cards'),
        ),
        migrations.AlterField(
            model_name='generationsession',
            name='difficulty',
            field=models.CharField(default='medium', max_length=20),
        ),
    ]
