# Generated by Django 4.2 on 2026-03-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_flashcard_practice_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='practice_questions',
        ),
    ]
